### ISSUE TITLE
Project with path ':flutter' could not be found in project ':app'

### ISSUE THREAD

**Issue by ttssttssttss** [persilee/android_ctrip#2]
我直接gradle build的，出现上述错误

**Comment by persilee** [comment]
请参照我的开发环境，flutter 版本是：Flutter 1.9.1+hotfix.6 • channel stable
貌似新版的flutter在建立flutter module时不会生成flutter模块。

**Comment by HuaZaiWuDi** [comment]
这个有办法解决吗？现在一直搜索不要“:Flutter”

**Comment by persilee** [comment]
这个是没有生成 Flutter 模块，一般都是 flutter sdk 版本问题，你把 flutter 版本切换到：Flutter 1.9.1+hotfix.6 • channel stable 试试，也可以自己新建一个 flutter 模块，把项目里的 dart 代码拷贝过去...

**Comment by tom1993721** [comment]
![image](https://user-images.githubusercontent.com/17629646/161453976-704d445d-1878-4bd4-a441-da95ae259623.png)


> 这个是没有生成 Flutter 模块，一般都是 flutter sdk 版本问题，你把 flutter 版本切换到：Flutter 1.9.1+hotfix.6 • channel stable 试试，也可以自己新建一个 flutter 模块，把项目里的 dart 代码拷贝过去...

![image](https://user-images.githubusercontent.com/17629646/161453998-9d79e521-8976-483a-9f58-f2fc6df3fbef.png)

你说的两个方法我都试过了，sdk版本对应上了也不会生成，拷贝也不行，还会出现咋办，是不是我拷贝错了？

**Comment by tom1993721** [comment]
![image](https://user-images.githubusercontent.com/17629646/161454107-6e9e0900-db4e-49b8-b24a-8c0f374b308e.png)


> 这个是没有生成 Flutter 模块，一般都是 flutter sdk 版本问题，你把 flutter 版本切换到：Flutter 1.9.1+hotfix.6 • channel stable 试试，也可以自己新建一个 flutter 模块，把项目里的 dart 代码拷贝过去...

我sdk版本下载一致了，也不会自动生成flutter模块，自己手动添加拷贝也不行，是不是拷贝得不对？
